_target_: src.model.ModelPyG
lr: ${learning_rate}
training_noise: ${training_noise}
batch_size: ${batch_size}

net: 
  _target_: src.model.baseline.BaselineDifference
  input_size: ${input_size}
  lookback: ${lookback}
  spatial_dimensions: ${spatial_dimensions}
