
_target_: src.model.ModelPyG
lr: ${learning_rate}
training_noise: ${training_noise}
batch_size: ${batch_size}

net: 
  _target_: src.model.cloud.FeaStNet
  input_size: ${input_size}
  lookback: ${lookback}
  hidden_size: 64
  hidden_layers: 3
  input_layer_heads: 10
  hidden_layer_heads: 10
  output_layer_heads: 10
  spatial_dimensions: ${spatial_dimensions}
