_target_: src.model.ModelPyG
lr: ${learning_rate}
training_noise: ${training_noise}
batch_size: ${batch_size}

net: 
  _target_: src.model.gnn.GCN
  input_size: ${input_size}
  lookback: ${lookback}
  hidden_size: 256
  hidden_layers: 3
  spatial_dimensions: ${spatial_dimensions}
