_target_: src.model.cloud.PointTransformer
input_size: ${input_size}
lookback: ${lookback}
hidden_size: 64
pos_nn_hidden_size: 64
pos_nn_hidden_layers: 2
attn_nn_hidden_size: 64
attn_nn_hidden_layers: 2
hidden_layers: 4
spatial_dimensions: ${spatial_dimensions}


