_target_: dynabench.model.cloud.PointTransformer
input_size: ${input_size}
lookback: ${lookback}
hidden_size: 64
pos_nn_hidden_size: 64
pos_nn_hidden_layers: 4
attn_nn_hidden_size: 64
attn_nn_hidden_layers: 4
hidden_layers: 4
spatial_dimensions: ${spatial_dimensions}


