_target_: dynabench.model.cloud.PointGNN
input_size: ${input_size}
lookback: ${lookback}
intermediate_hidden_size: 64
hidden_size: 64
encoder_nn_hidden_size: 64
encoder_nn_hidden_layers: 2
decoder_nn_hidden_size: 64
decoder_nn_hidden_layers: 2
offset_nn_hidden_size: 64
offset_nn_hidden_layers: 2
local_nn_hidden_size: 64
local_nn_hidden_layers: 2
global_nn_hidden_size: 64
global_nn_hidden_layers: 2
hidden_layers: 4
spatial_dimensions: ${spatial_dimensions}


