_target_: dynabench.generator.PDESolver

# general settings
# SHOULD NOT BE CHANGED
grid_size: 64
t_range: 200
dt: 1e-3
save_interval: 1
num_points: [15, 22, 30]
num_points_names: ["low", "med", "high"]

# save settings
# can be changed if only part of the dataset is needed
save_full_grid: True
save_full_cloud: True
save_cloud_points: True
save_grid_points: True