_target_: src.generator.PDESolver

# general settings
# SHOULD NOT BE CHANGED
grid_size: 64
t_range: 100
dt: 1e-3
save_interval: 0.1
num_points: [15, 30]
num_points_names: ["low", "high"]

# save settings
# can be changed if only part of the dataset is needed
save_full_grid: False
save_full_cloud: False
save_cloud_points: True
save_grid_points: True