_target_: pytorch_lightning.Trainer

accelerator: "gpu"
devices: 1
max_epochs: 1
default_root_dir: output

logger: 
  - _target_: pytorch_lightning.loggers.TensorBoardLogger
    save_dir: output/tb_logs
    name: test
    max_queue: 100
    flush_secs: 120
  - _target_: pytorch_lightning.loggers.CSVLogger
    save_dir: "output/csv_logs"
    name: test
    flush_logs_every_n_steps: 100
callbacks:
  - _target_: pytorch_lightning.callbacks.ModelCheckpoint
    monitor: val_loss
    save_last: True
    save_top_k: 1
    mode: min
  - _target_: pytorch_lightning.callbacks.early_stopping.EarlyStopping
    monitor: val_loss
    min_delta: 0.0
    patience: 5
    mode: min





