_target_: pytorch_lightning.Trainer

accelerator: "gpu"
devices: 1
limit_train_batches: 5
limit_test_batches: 5
max_epochs: 10
default_root_dir: ${output_dir}

logger: 
  - _target_: pytorch_lightning.loggers.TensorBoardLogger
    save_dir: ${output_dir}/tb_logs
    name: ${logdir}
    max_queue: 100
    flush_secs: 120
  - _target_: pytorch_lightning.loggers.CSVLogger
    save_dir: ${output_dir}/csv_logs
    name: ${logdir}
    flush_logs_every_n_steps: 100
callbacks:
  - _target_: pytorch_lightning.callbacks.ModelCheckpoint
    monitor: val_loss
    save_last: True
    save_top_k: 1
    mode: min
  - _target_: pytorch_lightning.callbacks.early_stopping.EarlyStopping
    monitor: val_loss
    min_delta: 0.0
    patience: 5
    mode: min





