_target_: src.dataset.DynaBenchDataModule
equation: ${experiment.equation}
task: ${experiment.task}
support: ${experiment.support}
num_points: ${experiment.num_points}
lookback: ${lookback}
rollout: ${rollout}
structure: torch