defaults:
  - model: resnet
  - datamodule: torch
  - lightningmodule: gridmodule
  - equation: wave
  - support: grid
  - num_points: high
  - trainer: default
  - _self_

lookback: 8
rollout: 17
batch_size: 16
learning_rate: 0.001
training_noise: 0.1
spatial_dimensions: 2
input_size: ${equation.num_fields}
output_dir: output
version_name: Null

logdir: ${experiment.support}/${experiment.num_points}/${experiment.equation}/${experiment.model}


experiment:
  equation: ${hydra:runtime.choices.equation}
  support: ${hydra:runtime.choices.support}
  num_points: ${hydra:runtime.choices.num_points}
  model: ${hydra:runtime.choices.model}

hydra:
  run:
    dir: ./${output_dir}/hydra/${logdir}/${now:%Y-%m-%d}_${now:%H-%M-%S}