name: "Docs"

on: [release, workflow_dispatch]

jobs:
  build-and-deploy-docs:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Set up Poetry
      uses: abatilo/actions-poetry@v3.0.0
      with:
          poetry-version: "1.8.2"

    - name: Install dependencies
      # install all requirements
      run: poetry install

    - name: Build documentation with sphinx
      run: poetry run sphinx-build -M html docs/source docs/build

    - name: Create .nojekyll file
      run: touch docs/build/html/.nojekyll

    - name: Push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        # Move contents of docs/build/html to the root
        rsync -a docs/build/html/ .
        git add -f .
        git commit -m "Update docs"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/dynabench/dynabench.github.io.git HEAD:master
