name: "Docs"

on: [push]

jobs:
  build:
    strategy:
      matrix:
        poetry-version: ["1.8.2"]
        python-version: ["3.12"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up Poetry
      uses: abatilo/actions-poetry@v3.0.0
      with:
          poetry-version: ${{ matrix.poetry-version }}

    - name: Install dependencies
      # install all requirements
      run: poetry install

    - name: Build documentation with sphinx
      run: poetry run sphinx-build -M html docs/source docs/build

    - name: Push generated docs to dynabench.github.io
      uses: nkoppel/push-files-to-another-repository@v1.1.3
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-files: 'docs/build/'
        destination-username: 'dynabench'
        destination-repository: 'dynabench.github.io'
        commit-email: 'andzej.dulny@gmail.com'