_target_: dynabench.generator.ProblemDescription
equation: gasdynamics
equation_params: 
  gamma: 2
  k: 0.1
  M: 2
  mu: 0.01
  rate: 1
grid_size: [64, 64]
domain_bounds: [64,64]
step_size: 0.01
save_dt: 1
t_max: 200