_target_: dynabench.generator.ProblemDescription
equation: reactiondiffusion
equation_params: 
  diffusivity_1: 0.1
  diffusivity_2: 0.001
  k: 0.005
  reaction_speed_1: 1
  reaction_speed_2: 1
  rate: 1
grid_size: [64, 64]
domain_bounds: [64,64]
step_size: 0.01
save_dt: 1
t_max: 200